// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlvI8O1DKwBEO1re7ChF9pFRkCd_oK2MM',
    appId: '1:10706715734:web:1a95d5e5522438f87667f7',
    messagingSenderId: '10706715734',
    projectId: 'health-monitor-18283',
    authDomain: 'health-monitor-18283.firebaseapp.com',
    databaseURL: 'https://health-monitor-18283-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-monitor-18283.appspot.com',
    measurementId: 'G-BC76SWF0K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWDBXkESI5IcJq8ZZRN-7KHGs_QSxX18',
    appId: '1:10706715734:android:59ec0a1a691c922b7667f7',
    messagingSenderId: '10706715734',
    projectId: 'health-monitor-18283',
    databaseURL: 'https://health-monitor-18283-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-monitor-18283.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnJfaPFixxTKUTH9r6Wx2zzhaXhONyiQ',
    appId: '1:10706715734:ios:c509840d1ba273ed7667f7',
    messagingSenderId: '10706715734',
    projectId: 'health-monitor-18283',
    databaseURL: 'https://health-monitor-18283-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-monitor-18283.appspot.com',
    iosClientId: '10706715734-09b4il6552gr49k7ko0aj2s51b39avkf.apps.googleusercontent.com',
    iosBundleId: 'com.autobonics.hydropodHydroponics',
  );
}
